version: '3.3' 

services: 
  redis:
    image: registry.fieespoch.edu.ec/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    command: 
      - redis-server
      - "--requirepass \"${REDIS_PASSWORD?Variable not set}\""
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.1"
          memory: 200M
      restart_policy:
        condition: on-failure
    volumes:
      - /hosthome/DockerCompose/Redis/redis-data:/var/lib/redis
      - /hosthome/DockerCompose/Redis/data:/data
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true


